THEMES = {
    "kawaii_pink": {
        "bg_left_start": "#EAF2FA",
        "bg_left_end": "#6CA0DC",
        "bg_right_start": "#F7E3E9",
        "bg_right_end": "#D98BAC",
        "button_color": "#FFDDE6",
        "active_button": "#FFBBD0",
        "text_bg": "#FFF8FC",
        "text_fg": "black",
        "main_bg": "#C7D3E3",
        "calendar_day_bg": "white",
        "settings_text_fg": "black",
        "calendar_day_fg": "black",
        "border_color": "#E0E0E0",
        "calendar_bg_start": "#eaf3fa",
        "calendar_bg_end": "#eaf3fa",
        "mood_tracker_bg_start": "#f8e3ea",
        "mood_tracker_bg_end": "#f8e3ea",
        "text_editor_buttons_bg_start": "#f8e3ea",
        "text_editor_buttons_bg_end": "#f8e3ea"
    },
    "dark_mode": {
        "bg_left_start": "#2E2E2E",
        "bg_left_end": "#000000",
        "bg_right_start": "#1C1C1C",
        "bg_right_end": "#000000",
        "button_color": "#4A4A4A",
        "active_button": "#6A6A6A",
        "text_bg": "#3C3C3C",
        "text_fg": "white",
        "main_bg": "#000000",
        "calendar_day_bg": "#4A4A4A",
        "settings_text_fg": "white",
        "calendar_day_fg": "white",
        "border_color": "#000000",
        "calendar_bg_start": "#292929",
        "calendar_bg_end": "#151515",
        "mood_tracker_bg_start": "#1b1b1b",
        "mood_tracker_bg_end": "#161616",
        "text_editor_buttons_bg_start": "#030303",
        "text_editor_buttons_bg_end": "#000000"
    },
    "xbox": {
        "bg_left_start": "#3C3C3C",
        "bg_left_end": "#000000",
        "bg_right_start": "#107C10",
        "bg_right_end": "#0A4D0A",
        "button_color": "#90D090",
        "active_button": "#A0E0A0",
        "text_bg": "#505050",
        "text_fg": "white",
        "main_bg": "#202020",
        "calendar_day_bg": "#505050",
        "settings_text_fg": "white",
        "calendar_day_fg": "#3dff3d",
        "border_color": "#000000",
        "calendar_bg_start": "#363636",
        "calendar_bg_end": "#1c1c1c",
        "mood_tracker_bg_start": "#0f7b0e",
        "mood_tracker_bg_end": "#0c7211",
        "text_editor_buttons_bg_start": "#09530a",
        "text_editor_buttons_bg_end": "#0b4e09"
    },
    "galaxy": {
        "bg_left_start": "#502894",
        "bg_left_end": "#13042e",
        "bg_right_start": "#090947",
        "bg_right_end": "#000000",
        "button_color": "#9F5F80",
        "active_button": "#FF847C",
        "text_bg": "#2A2A55",
        "text_fg": "#E5DDCB",
        "main_bg": "#1A1A3D",
        "calendar_day_bg": "#2A2A55",
        "settings_text_fg": "#E5DDCB",
        "calendar_day_fg": "#E5DDCB",
        "border_color": "#000000",
        "calendar_bg_start": "#4a238d",
        "calendar_bg_end": "#2e1560",
        "mood_tracker_bg_start": "#080844",
        "mood_tracker_bg_end": "#070838",
        "text_editor_buttons_bg_start": "#010109",
        "text_editor_buttons_bg_end": "#000000"
    },
    "pastel": {
        "bg_left_start": "#FFADAD",
        "bg_left_end": "#FF6961",
        "bg_right_start": "#FFD6A5",
        "bg_right_end": "#FF9861",
        "button_color": "#FDFFB6",
        "active_button": "#CAFFBF",
        "text_bg": "#9BF6FF",
        "text_fg": "black",
        "main_bg": "#A0C4FF",
        "calendar_day_bg": "#FDFFB6",
        "settings_text_fg": "black",
        "calendar_day_fg": "black",
        "border_color": "#E0E0E0",
        "calendar_bg_start": "#ffa4a8",
        "calendar_bg_end": "#fb8b85",
        "mood_tracker_bg_start": "#fed4a2",
        "mood_tracker_bg_end": "#fec997",
        "text_editor_buttons_bg_start": "#f8a26e",
        "text_editor_buttons_bg_end": "#fd9e68"
    },
    "windows_95": {
        "bg_left_start": "#C0C0C0",
        "bg_left_end": "#C0C0C0",
        "bg_right_start": "#C0C0C0",
        "bg_right_end": "#C0C0C0",
        "button_color": "#C0C0C0",
        "active_button": "#A0A0A0",
        "text_bg": "white",
        "text_fg": "black",
        "main_bg": "#008080",
        "calendar_day_bg": "white",
        "settings_text_fg": "black",
        "calendar_day_fg": "black",
        "border_color": "black",
        "calendar_bg_start": "#c0c0c0",
        "calendar_bg_end": "#c0c0c0",
        "mood_tracker_bg_start": "#c0c0c0",
        "mood_tracker_bg_end": "#c0c0c0",
        "text_editor_buttons_bg_start": "#c0c0c0",
        "text_editor_buttons_bg_end": "#c0c0c0"
    },
    "sunset": {
        "bg_left_start": "#8B0000",
        "bg_left_end": "#FF8C00",
        "bg_right_start": "#FF8C00",
        "bg_right_end": "#FFD700",
        "button_color": "#CD853F",
        "active_button": "#DAA520",
        "text_bg": "#2F4F4F",
        "text_fg": "white",
        "main_bg": "#4B0082",
        "calendar_day_bg": "#2F4F4F",
        "settings_text_fg": "white",
        "calendar_day_fg": "white",
        "border_color": "black",
        "calendar_bg_start": "#920d01",
        "calendar_bg_end": "#c84901",
        "mood_tracker_bg_start": "#ff8e01",
        "mood_tracker_bg_end": "#ff9b00",
        "text_editor_buttons_bg_start": "#fece00",
        "text_editor_buttons_bg_end": "#ffd502"
    },
 
"ocean": {
    "bg_left_start": "#A7D8F0",
    "bg_left_end":   "#2A6FA1",
    "bg_right_start":"#E0F7FA",
    "bg_right_end":  "#80DEEA",
    "button_color":  "#4FC3F7",
    "active_button": "#29B6F6",
    "text_bg":       "#FFFFFF",
    "text_fg":       "#01579B",
    "main_bg":       "#B3E5FC",
    "calendar_day_bg":"white",
    "settings_text_fg":"black",
    "calendar_day_fg":"black",
    "border_color":  "#B0BEC5",
    "calendar_bg_start": "#9bcee9",
    "calendar_bg_end":   "#669fc4",
    "mood_tracker_bg_start": "#def7fb",
    "mood_tracker_bg_end":   "#ccf1f7",
    "text_editor_buttons_bg_start": "#8de1ec",
    "text_editor_buttons_bg_end":   "#83dfec"
},
"cyber": {
    "bg_left_start": "#0D001A",
    "bg_left_end":   "#1A0033",
    "bg_right_start":"#12002B",
    "bg_right_end":  "#2E0047",
    "button_color":  "#FF00FF",
    "active_button": "#FF66FF",
    "text_bg":       "#1E0038",
    "text_fg":       "#00FFFF",
    "main_bg":       "#0A0014",
    "calendar_day_bg":"#2A0044",
    "settings_text_fg":"#00FFFF",
    "calendar_day_fg":"#00FFFF",
    "border_color":  "#FF00FF",
    "calendar_bg_start": "#0e001c",
    "calendar_bg_end":   "#120026",
    "mood_tracker_bg_start": "#12002a",
    "mood_tracker_bg_end":   "#17002f",
    "text_editor_buttons_bg_start": "#290042",
    "text_editor_buttons_bg_end":   "#2b0045"
}

    
}